version: '3'
services:
  space-engineers-server:
    image: space-engineers-server
    container_name: registry.kedi-server.de/space_engineers_server:latest
    ports:
      - "27016:27016/tcp"
      - "27016:27016/udp"
      - "8888:8080"
    restart: unless-stopped
